### ISSUE TITLE
[RFC][Routing] Controllers in sub folders

### ISSUE THREAD

**Issue by leevigraham** [KnpLabs/KnpRadBundle#59] opened 2013-02-28 10:19 UTC
I like to keep my Controllers namespaced depending on their purpose. For example:
- App/Controllers/Api/ProjectsController
- App/Controllers/Admin/ProjectsController
- App/Controllers/App/ProjectsController

Is this currently possible in KnpRadBundle if not would a pull request be in scope of the project.

**Comment by docteurklein** [comment] 2013-02-28 13:27
yes it's possible: just use

```
App:Api\Projects: ~

```

in your routing.

duplicate of #53

**Closed as completed by docteurklein** 2013-02-28 13:27 UTC
